package se.experis.assignmentthree.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import se.experis.assignmentthree.models.Character;

import java.util.List;

//Repository for all the character specific SQL functions generated by Hibernate
@Repository
public interface CharacterRepository extends JpaRepository<Character,Long> {
    //Finds all characters with a character id matching franchise id (input) and returns a list
    List<Character> findAllByFranchiseId(Long id);
    //Finds a specific character with a character id matching the input id and returns the object
    Character getCharacterById(Long id);
    //Finds a specific character with a character id matching the input id and deletes the object
    Character deleteCharacterById(Long id);


}
