package se.experis.assignmentthree.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import se.experis.assignmentthree.models.Movie;

import java.util.List;
//Repository for all the Movie specific SQL functions generated by Hibernate
@Repository
public interface MovieRepository extends JpaRepository<Movie, Long> {
    //Finds all movies with a movie id matching franchise id (input) and returns a list
    List<Movie> getAllByFranchiseId(Long franchise_id);
    //Finds a specific movie with a movie id matching the input id and returns the object
    Movie findMovieById(Long id);
    Movie deleteMovieById(Long id);



}
